# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-10 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20190110_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=280)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField(blank=True)),
                ('received_by_volunteer', models.BooleanField(default=False)),
                ('received_by_center', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at_volunteer', models.DateTimeField(blank=True)),
                ('received_at_center', models.DateTimeField(blank=True)),
                ('donating_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='goonj_sessions.DonatingSession')),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Donator')),
            ],
        ),
    ]
