# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190108_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=8)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoonjCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dropping_center', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('start_time', models.TimeField(default='10:00')),
                ('end_time', models.TimeField(default='17:00')),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='country',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='donating_session_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='goonj_center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GoonjCenter'),
        ),
        migrations.AddField(
            model_name='worker',
            name='goonj_center',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.GoonjCenter'),
        ),
    ]
