# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-13 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190110_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goonjcenter',
            name='address',
            field=models.CharField(max_length=600),
        ),
    ]
